name: Add Repository to CircleCI

on:
  repository_dispatch:
    types: [repository_created]
jobs:
  add_to_circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Curl
        run: sudo apt-get install -y curl

      - name: Add Repository to CircleCI
        env:
          CIRCLECI_API_TOKEN: ${{ secrets.CIRCLECI_API_TOKEN }}  # CircleCI APIトークン
          GITHUB_REPO_NAME: ${{ github.event.repository.name }}  # リポジトリ名
          GITHUB_REPO_OWNER: ${{ github.event.repository.owner.login }}  # リポジトリオーナー
        run: |
          curl -u ${CIRCLECI_API_TOKEN}: \
            -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "name": "'${GITHUB_REPO_NAME}'",
              "vcs-type": "github",
              "username": "'${GITHUB_REPO_OWNER}'"
            }' \
            https://circleci.com/api/v1.1/project/github/${GITHUB_REPO_OWNER}/${GITHUB_REPO_NAME}/follow
