site_name: ${{ values.app_name }}
site_description: ${{ values.description }}
repo_url: https://${{ values.git_host_url }}/${{ values.git_owner_name }}/${{ values.app_name }}-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - ${{ values.app_name }} Documentation: index.md
