---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${{ values.app_name }}-sa
imagePullSecrets:
  - name: quay-credentials  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${{ values.app_name }}-sa-admin
subjects:
- kind: ServiceAccount
  name: ${{ values.app_name }}-sa 
  namespace: ${{ values.namespace }}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
