apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${{ values.app_name }}
  name: ${{ values.app_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ${{ values.app_name }}
  template:
    metadata:
      labels:
        app: ${{ values.app_name }}
        answer1: ${{ values.answer_1 }}
        answer2: ${{ values.answer_2 }}
        kubecraft: "true"
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: ${{ values.image_registry }}/${{ values.namespace }}/${{ values.app_name }}:latest
        name: ${{ values.app_name }}
        ports:
        - containerPort: 3000
          protocol: TCP
        imagePullPolicy: Always
      serviceAccountName: ${{ values.app_name }}-sa
