apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: ${{ values.app_name }}
  name: ${{ values.app_name }}
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: ${{ values.app_name }}
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
