apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: ${{ values.app_name }}-trigger-binding
spec:
  params:
    - name: app-name
      value: ${{ values.app_name }}
    - name: git-app-rev
      #value: $(body.head_commit.id)
      value: main
    - name: git-app-url
      value: 'https://${{ values.git_host_url }}/${{ values.git_owner_name }}/${{ values.app_name }}'
    - name: git-user
      value: $(body.pusher.name)
    - name: git-email
      value: $(body.pusher.email)
