apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: ${{ values.app_name }}-production

images:
- digest: sha256:085b9d73976428c1f6c2966fd6292306a6d2c60e1f6a5648fcc7b303f937f076
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: quay-registry-quay-quay.apps.rosa.rosa-hcp-1544.fnn1.p3.openshiftapps.com/skitamura-quay-org/${{ values.app_name }}-develop/${{ values.app_name }}-record
